spin_manifest_version = 2

[application]
name = "spin"
version = "0.1.0"
authors = ["Alejandro Alonso López <aalonsopersonal@gmail.com>"]
description = ""

[[trigger.http]]
route = "/..."
component = "spin"

[component.spin]
source = "target/wasm32-wasi/release/spin.wasm"
allowed_outbound_hosts = []
[component.spin.build]
command = "cargo build --target wasm32-wasi --release"
watch = ["src/**/*.rs", "Cargo.toml"]
